clear

load("example_log.mat")
t = out.time_s';
angles = out.actAng_deg';
desired_angles = out.desAng_deg';
pos = out.actPos_m';
des_pos = out.desPos_m';

%% Multi plot example
plot_settings(t, angles, 'data_name', 'angles', ...
    'desired_data', desired_angles, ...
    'labels', {'Roll', 'Pitch', 'Yaw'}, ...
    'units', 'deg', ...
    'colors', {'blue', 'red'}, ...
    'legend_labels', {'Actual', 'Desired'}, ...
    'figure_size', [400 400 800 600]);
sgtitle('Multi Plot Example');
exportgraphics(gcf,'MultiPlot.png','Resolution',600)

%% Spesific plot example
plot_settings(t, angles, 'data_name', 'angles', ...
    'desired_data', desired_angles, ...
    'indices', [1 2], ...
    'labels', {'Roll', 'Pitch'}, ...
    'units', 'deg', ...
    'colors', {'blue', 'red'}, ...
    'legend_labels', {'Actual', 'Desired'});
sgtitle(gcf, 'Spesific Indices Example');
exportgraphics(gcf,'SpesificPlot.png','Resolution',600)

%% Single plot example
plot_settings(t, angles, 'subplot_layout', 'single', ...
    'labels', {'Angles'}, ...
    'units', 'deg', ...
    'legend_labels', {'Roll', 'Pitch', 'Yaw'});
sgtitle('Single Plot Example');
exportgraphics(gcf,'SinglePlot.png','Resolution',600)





